# Generated by Django 4.2.20 on 2025-05-10 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('document', 'Document')], max_length=20)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GMOProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('crop_type', models.CharField(choices=[('corn', 'Corn'), ('soybeans', 'Soybeans'), ('cotton', 'Cotton'), ('canola', 'Canola'), ('rice', 'Rice'), ('wheat', 'Wheat'), ('sugarbeet', 'Sugarbeet'), ('alfalfa', 'Alfalfa'), ('potato', 'Potato'), ('tomato', 'Tomato')], max_length=20)),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], max_length=20)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('certification_id', models.CharField(blank=True, max_length=50)),
                ('certification_date', models.DateField(blank=True, null=True)),
                ('certification_authority', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('qr_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=100)),
                ('verification_method', models.CharField(choices=[('qr', 'QR Code'), ('manual', 'Manual Entry'), ('image', 'Image Upload')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.gmoproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_user', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
