# Generated by Django 5.2.1 on 2025-05-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_webinar_remove_chatmessage_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMOKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('science', 'GMO Science'), ('regulations', 'Regulations'), ('crops', 'Specific Crops'), ('verification', 'Product Verification'), ('myths', 'Myths & Facts')], max_length=20)),
                ('question_patterns', models.TextField(help_text='One per line, common question patterns')),
                ('answer', models.TextField()),
                ('references', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('confidence_score', models.FloatField(default=1.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_agriculture_related',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='context',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_helpful',
            field=models.BooleanField(null=True),
        ),
    ]
