# Generated by Django 5.2.1 on 2025-05-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_gmoknowledgebase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmoproduct',
            name='qr_data',
            field=models.TextField(blank=True),
        ),
    ]
